In [1]:
#Librerias de Datos
import pandas as pd
import numpy as np
import pickle as pc

In [2]:
#Librerias para entrenar el Modelo
from sklearn.naive_bayes import GaussianNB

Ejecucion de nueva consulta:

In [3]:
new_query=[1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,1,0,0,0]
new_query= np.array(new_query)
new_query=np.reshape(new_query,(1,19))
new_query.shape
new_query

array([[1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0]])

In [4]:
modelo_riego=pc.load(open('/content/sample_data/ModeloComprobacionRiego.pkl','rb'))

In [5]:
modelo_riego_Arbol=pc.load(open('/content/sample_data/ModeloComprobacionRiegoArbol.pkl','rb'))

In [6]:
y_predict=modelo_riego.predict(new_query)
y_predict

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([65])

In [7]:
y_predict=modelo_riego_Arbol.predict(new_query)
y_predict

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([65])